const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"客服聊天管理",
                        "menuJump":"列表",
                        "tableName":"chat"
                    }
                ],
                "menu":"客服聊天管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"产品类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJinronggongju"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"投资类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLicaichanpin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"风险等级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLicaichanpinFengxian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"银行管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYinhang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"银行卡类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYinhangka"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"金融工具管理",
                        "menuJump":"列表",
                        "tableName":"jinronggongju"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"金融工具评价管理",
                        "menuJump":"列表",
                        "tableName":"jinronggongjuCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"金融工具收藏管理",
                        "menuJump":"列表",
                        "tableName":"jinronggongjuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"借款管理",
                        "menuJump":"列表",
                        "tableName":"jinronggongjuOrder"
                    }
                ],
                "menu":"金融工具管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"理财产品管理",
                        "menuJump":"列表",
                        "tableName":"licaichanpin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"理财产品评价管理",
                        "menuJump":"列表",
                        "tableName":"licaichanpinCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"理财产品收藏管理",
                        "menuJump":"列表",
                        "tableName":"licaichanpinCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"理财产品订单管理",
                        "menuJump":"列表",
                        "tableName":"licaichanpinOrder"
                    }
                ],
                "menu":"理财产品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"银行卡管理",
                        "menuJump":"列表",
                        "tableName":"yinhangka"
                    }
                ],
                "menu":"银行卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"存款管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkaCunkuan"
                    }
                ],
                "menu":"存款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"银行卡记录管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkaJilu"
                    }
                ],
                "menu":"银行卡记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"取款管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkaQukuan"
                    }
                ],
                "menu":"取款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"转账管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkaZhuanzhang"
                    }
                ],
                "menu":"转账管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"员工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
    ,
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"客服聊天管理",
                                "menuJump":"列表",
                                "tableName":"chat"
                            }
                        ],
                        "menu":"客服聊天管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"公告信息管理",
                                "menuJump":"列表",
                                "tableName":"gonggao"
                            }
                        ],
                        "menu":"公告信息管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"金融工具管理",
                                "menuJump":"列表",
                                "tableName":"jinronggongju"
                            }
                            ,
                            {
                                "buttons":[
                                    "审核",
                                    "查看"
                                ],
                                "menu":"借款管理",
                                "menuJump":"列表",
                                "tableName":"jinronggongjuOrder"
                            }
                        ],
                        "menu":"金融工具管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"理财产品管理",
                                "menuJump":"列表",
                                "tableName":"licaichanpin"
                            }
                            ,
                            {
                                "buttons":[
                                    "审核",
                                    "查看"
                                ],
                                "menu":"理财产品订单管理",
                                "menuJump":"列表",
                                "tableName":"licaichanpinOrder"
                            }
                        ],
                        "menu":"理财产品管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"银行卡管理",
                                "menuJump":"列表",
                                "tableName":"yinhangka"
                            }
                        ],
                        "menu":"银行卡管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"银行卡记录管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaJilu"
                            }
                        ],
                        "menu":"银行卡记录管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"存款管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaCunkuan"
                            }
                        ],
                        "menu":"存款管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"取款管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaQukuan"
                            }
                        ],
                        "menu":"取款管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"转账管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaZhuanzhang"
                            }
                        ],
                        "menu":"转账管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"用户管理",
                                "menuJump":"列表",
                                "tableName":"yonghu"
                            }
                        ],
                        "menu":"用户管理"
                    }
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"员工",
                "tableName":"yuangong"
            }
            ,
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"公告信息管理",
                                "menuJump":"列表",
                                "tableName":"gonggao"
                            }
                        ],
                        "menu":"公告信息管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"金融工具管理",
                                "menuJump":"列表",
                                "tableName":"jinronggongju"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"金融工具评价管理",
                                "menuJump":"列表",
                                "tableName":"jinronggongjuCommentback"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "删除"
                                ],
                                "menu":"金融工具收藏管理",
                                "menuJump":"列表",
                                "tableName":"jinronggongjuCollection"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"借款管理",
                                "menuJump":"列表",
                                "tableName":"jinronggongjuOrder"
                            }
                        ],
                        "menu":"金融工具管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"理财产品评价管理",
                                "menuJump":"列表",
                                "tableName":"licaichanpinCommentback"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "删除"
                                ],
                                "menu":"理财产品收藏管理",
                                "menuJump":"列表",
                                "tableName":"licaichanpinCollection"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"理财产品订单管理",
                                "menuJump":"列表",
                                "tableName":"licaichanpinOrder"
                            }
                        ],
                        "menu":"理财产品管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"银行卡管理",
                                "menuJump":"列表",
                                "tableName":"yinhangka"
                            }
                        ],
                        "menu":"银行卡管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"银行卡记录管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaJilu"
                            }
                        ],
                        "menu":"银行卡记录管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"存款管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaCunkuan"
                            }
                        ],
                        "menu":"存款管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"取款管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaQukuan"
                            }
                        ],
                        "menu":"取款管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"转账管理",
                                "menuJump":"列表",
                                "tableName":"yinhangkaZhuanzhang"
                            }
                        ],
                        "menu":"转账管理"
                    }
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"用户",
                "tableName":"yonghu"
            }
]
    }
}
export default menu;
